name: golangci-lint
on: [push, pull_request]
jobs:
    resolve-modules:
        name: Resolve Modules
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - name: Checkout Sources
              uses: actions/checkout@v2
            - id: set-matrix
              run: ./cmd/resolve_go_modules.sh
    golangci:
        name: Linter
        needs: resolve-modules
        runs-on: ubuntu-latest
        strategy:
            matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                  go-version: "1.21"
                  cache: false
            - uses: actions/checkout@v3
            - name: golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: "v1.54"
                  working-directory: ${{ matrix.workdir }}
                  only-new-issues: true
